name: YK's New Blog
description: study & others
meta_description: "Codes and life stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 12
baseurl: ""
domain_name: "http://Poiurity.github.io"
asset_url: /assets
google_analytics: "UA-XXXXXXXX-X"
comment:
    provider: "disqus"
    disqus:
      shortname: "poiurity"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "LEE YEONGUK"

# Disqus config
disqus-shortname: ""
